#pragma once

#define EXPLORER_SELECTOR_VERSION_MAJOR 0
#define EXPLORER_SELECTOR_VERSION_MINOR 2
#define EXPLORER_SELECTOR_VERSION_PATCH 0
#define EXPLORER_SELECTOR_VERSION_BUILD 0

#define EXPLORER_SELECTOR_VERSION_STRING "0.2.0"
#define EXPLORER_SELECTOR_VERSION_STRING_4 "0.2.0.0"
